name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Runs on push to master (publishes package)
  pull_request:
    branches:
      - master  # Runs on PRs to master (build + test only)

permissions:
  contents: write

jobs:
  # ✅ Job for PRs: Build and Run Tests (Does NOT publish)
  build-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test --configuration Release --no-build --verbosity normal

  # ✅ Job for `master`: Build, Test, and Publish NuGet Package
  publish:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build-pr  # Ensures tests pass before publishing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Generate Version Number
        id: get_version
        run: |
          VERSION_PREFIX=$(cat EmailDomainValidator/EmailDomainValidator.csproj | grep -oPm1 '(?<=<VersionPrefix>)[^<]+')
          BUILD_NUMBER=${{ github.run_number }}
          FULL_VERSION="$VERSION_PREFIX.$BUILD_NUMBER"
          echo "VERSION=$FULL_VERSION" >> $GITHUB_ENV
          echo "Generated version: $FULL_VERSION"

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build --output nupkg /p:Version=${{ env.VERSION }}

      - name: Publish to NuGet
        if: success()
        run: dotnet nuget push nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Create GitHub Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          files: nupkg/*.nupkg
          draft: false
          prerelease: false
